-- USE master
-- GO
-- IF EXISTS (SELECT *
-- FROM sys.databases
-- WHERE NAME = 'DATAVERSE')
-- BEGIN
--     ALTER DATABASE DATAVERSE SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
--     DROP DATABASE DATAVERSE;
-- END
-- GO
-- CREATE DATABASE DATAVERSE
-- GO

-- IF EXISTS (SELECT *
-- FROM sys.server_principals
-- WHERE name = 'web')
-- DROP LOGIN web
-- GO
-- CREATE LOGIN web WITH PASSWORD=   N'Kenapa03,'
-- GO
-- USE DATAVERSE;
-- GO
-- CREATE USER web FOR LOGIN web
-- GO
-- GRANT EXEC,SELECT, DELETE, INSERT,UPDATE ON DATABASE::DATAVERSE TO web
-- GO

CREATE TABLE SUMBER_DAYA_ALAM
(
    Id INT NOT NULL PRIMARY KEY,
    NamaKomoditi VARCHAR(20) NOT NULL,
    NamaEnglish VARCHAR(20) NOT NULL,
    Jenis VARCHAR(20) NOT NULL
);

CREATE TABLE KEGUNAAN
(
    Id INT NOT NULL,
    Kegunaan VARCHAR(40) NOT NULL,
    FOREIGN KEY (Id) REFERENCES SUMBER_DAYA_ALAM(Id),
    PRIMARY KEY (Id, Kegunaan)
);


CREATE TABLE KEHUTANAN
(
    Id INT NOT NULL,
    FOREIGN KEY (Id) REFERENCES SUMBER_DAYA_ALAM(Id),
    Famili VARCHAR(20) NOT NULL,
    KesesuaianEkologis VARCHAR(20) NOT NULL,
    KepadatanKayu SMALLINT NOT NULL,
    PERTUMBUHAN SMALLINT NOT NULL
);

CREATE TABLE PERKEBUNAN
(
    Id INT NOT NULL,
    FOREIGN KEY (Id) REFERENCES SUMBER_DAYA_ALAM(Id),
    Famili VARCHAR(20) NOT NULL,
    SuhuOptimal FLOAT NOT NULL,
    WaktuPanen INT NOT NULL,
    JenisTanaman VARCHAR(20) NOT NULL
);

CREATE TABLE PERTAMBANGAN
(
    Id INT NOT NULL PRIMARY KEY,
    FOREIGN KEY (Id) REFERENCES SUMBER_DAYA_ALAM(Id),
    IdGolongan VARCHAR(20) NOT NULL,
    Asal VARCHAR(20) NOT NULL,
    Golongan VARCHAR(25) NOT NULL
);

CREATE TABLE MINERAL
(
    Id INT NOT NULL,
    FOREIGN KEY (Id) REFERENCES PERTAMBANGAN(Id),
    Kilau VARCHAR(20) NOT NULL,
    KlasifikasiMineral VARCHAR(20) NOT NULL,
    KekerasanMohs FLOAT NOT NULL,
    SistemKristal VARCHAR(20) NOT NULL
);

CREATE TABLE TANAH
(
    Id INT NOT NULL PRIMARY KEY,
    FOREIGN KEY (Id) REFERENCES PERTAMBANGAN(Id),
    Ukuran FLOAT NOT NULL,
    JenisTanah VARCHAR(20) NOT NULL
);

CREATE TABLE KANDUNGAN_TANAH
(
    Id INT NOT NULL,
    FOREIGN KEY (Id) REFERENCES TANAH(Id),
    Kandungan VARCHAR(20) NOT NULL,
    PRIMARY KEY (Id, Kandungan)
);

CREATE TABLE MINYAK_BUMI
(
    Id INT NOT NULL,
    FOREIGN KEY (Id) REFERENCES PERTAMBANGAN(Id),
    TitikDidih SMALLINT NOT NULL,
    JumlahAtom SMALLINT NOT NULL
);

CREATE TABLE WILAYAH
(
    Id INT NOT NULL PRIMARY KEY,
    Kota VARCHAR(30) NOT NULL,
    Provinsi VARCHAR(30) NOT NULL,
    UnitGeografis VARCHAR(30) NOT NULL
);

CREATE TABLE PERUSAHAAN
(
    Id INT NOT NULL PRIMARY KEY,
    Nama VARCHAR(40) NOT NULL,
    Milik VARCHAR(10) NOT NULL,
    Sektor VARCHAR(20) NOT NULL,
    TahunBerdiri SMALLINT NOT NULL,
    Alamat VARCHAR(300) NOT NULL,
    Izin VARCHAR(100) NOT NULL,
    Jenis VARCHAR(20) NOT NULL,
    IdWilayah INT NOT NULL,
    FOREIGN KEY (IdWilayah) REFERENCES WILAYAH(Id),
    IdInduk INT,
    FOREIGN KEY (IdInduk) REFERENCES PERUSAHAAN(Id)
);

CREATE TABLE TELEPON
(
    Id INT NOT NULL,
    FOREIGN KEY (Id) REFERENCES PERUSAHAAN(Id),
    Telepon VARCHAR(20) NOT NULL,
    PRIMARY KEY (Id, Telepon)
);

CREATE TABLE PERUSAHAAN_SWASTA
(
    Id INT NOT NULL,
    FOREIGN KEY (Id) REFERENCES PERUSAHAAN(Id),
    IzinBerlaku DATE NOT NULL,
    IzinBerakhir DATE NOT NULl,
    idPerusahaanBeli INT,
    FOREIGN KEY (idPerusahaanBeli) REFERENCES PERUSAHAAN(Id),
    NamaOlahan VARCHAR(20)
);

CREATE TABLE BERADA_DI
(
    IdKota INT NOT NULL,
    FOREIGN KEY (IdKota) REFERENCES WILAYAH(Id),
    IdKomoditi INT NOT NULL,
    FOREIGN KEY (IdKomoditi) REFERENCES PERTAMBANGAN(Id),
    PejabatBertanggungJawab VARCHAR(20) NOT NULL,
    Angka BIGINT NOT NULL,
    Satuan VARCHAR(20) NOT NULL,
    PRIMARY KEY (IdKota, IdKomoditi, Angka)
);

CREATE TABLE MENGOLAH
(
    IdKota INT NOT NULL,
    FOREIGN KEY (IdKota) REFERENCES WILAYAH(Id),
    IdKomoditi INT NOT NULL,
    FOREIGN KEY (IdKomoditi) REFERENCES SUMBER_DAYA_ALAM(Id),
    IdPerusahaan INT NOT NULL,
    FOREIGN KEY (IdPerusahaan) REFERENCES PERUSAHAAN(Id),
    PRIMARY KEY (IdKota, IdKomoditi, IdPerusahaan),
    Luas BIGINT NOT NULL,
    Longitude FLOAT NOT NULL,
    Latitude FLOAT NOT NULL,
    JenisPengolahan VARCHAR(20) NOT NULL
);

CREATE TABLE HASIL
(
    IdKota INT NOT NULL,
    IdKomoditi INT NOT NULL,
    IdPerusahaan INT NOT NULL,
    FOREIGN KEY (IdKota, IdKomoditi, IdPerusahaan) REFERENCES MENGOLAH(IdKota, IdKomoditi, IdPerusahaan),
    Tahun SMALLINT NOT NULL,
    Angka BIGINT NOT NULL,
    Satuan VARCHAR(20) NOT NULL,
    Pendapatan BIGINT NOT NULL,
    PRIMARY KEY (IdKota, IdKomoditi, IdPerusahaan, Tahun)
);




 
