name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: DB_PASSWORD=${{ secrets.PASS }} docker-compose build
      - name: Test printing your secret (Remove this step in production)
        run: cat $HOME/secrets/my_secret.json
      - name: Run the Docker
        run: docker-compose up -d
